"use client";

import { useRouter } from "next/navigation";

export default function TermsPage() {
  const router = useRouter();
  const lastUpdated = "June 25, 2026";

  return (
    <main className="min-h-screen bg-[#1f1f1f] text-white px-6 py-10">
      <div className="mx-auto max-w-3xl">
        <button
          type="button"
          onClick={() => router.back()}
          className="mb-6 rounded-full border border-white/10 px-4 py-2 text-sm text-white/70 hover:text-white"
        >
          ← Back
        </button>

        <h1 className="text-4xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-sm text-white/40">Last updated: {lastUpdated}</p>

        <div className="mt-8 space-y-8 text-white/70 leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. About MultiLLM</h2>
            <p>
              MultiLLM ("we", "us", or "our") is a unified AI chat platform that lets you interact
              with multiple large language model providers — including OpenAI, Anthropic (Claude),
              Google Gemini, Groq, DeepSeek, and others — through a single streaming interface.
              These Terms govern your use of MultiLLM at <span className="text-white">multillm.net</span>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Acceptance of Terms</h2>
            <p>
              By creating an account or using MultiLLM, you agree to these Terms of Service and
              our Privacy Policy. If you do not agree, please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Your Account</h2>
            <p>
              You are responsible for maintaining the security of your account and all activity
              that occurs under it. You must be at least 13 years old to use MultiLLM. We reserve
              the right to suspend or terminate accounts that violate these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Premium Subscriptions</h2>
            <p>
              MultiLLM offers paid Premium plans (monthly and yearly) that unlock access to
              additional AI models and higher usage limits. Payments are processed securely by
              Paddle (paddle.com), who acts as the Merchant of Record for all transactions.
              By purchasing a Premium plan, you also agree to Paddle's terms of service.
            </p>
            <p className="mt-3">
              Subscription fees are billed in advance. Your plan will remain active until the
              end of the billing period. We do not offer automatic renewals by default — you
              control your subscription.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Acceptable Use</h2>
            <p>You agree not to use MultiLLM to:</p>
            <ul className="mt-3 space-y-2 list-disc list-inside">
              <li>Generate content that is illegal, harmful, or violates third-party rights</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the platform</li>
              <li>Share your account credentials with others</li>
              <li>Use the service to circumvent the usage policies of underlying AI providers</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. AI-Generated Content</h2>
            <p>
              MultiLLM provides access to third-party AI models. We do not control or take
              responsibility for the outputs generated by these models. AI responses may be
              inaccurate, incomplete, or outdated. Do not rely on AI-generated content for
              legal, medical, financial, or other professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Intellectual Property</h2>
            <p>
              You retain ownership of any content you input into MultiLLM. We do not claim
              ownership of your prompts or conversations. The MultiLLM platform, interface,
              and branding are our intellectual property and may not be copied or reused
              without permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Limitation of Liability</h2>
            <p>
              MultiLLM is provided "as is" without warranties of any kind. To the fullest
              extent permitted by law, we are not liable for any indirect, incidental, or
              consequential damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify you of material
              changes via email or an in-app notice. Continued use of MultiLLM after changes
              take effect constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Israel. Any disputes
              arising from these Terms shall be resolved in the courts of Israel.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Contact</h2>
            <p>
              Questions about these Terms? Email us at{" "}
              <a href="mailto:support@multillm.net" className="text-teal-400 hover:underline">
                support@multillm.net
              </a>
            </p>
          </section>

        </div>
      </div>
    </main>
  );
}
